log-reader:
  logDir: ${LOG_DIRECTORY:/var/logs}
  defaultLineLimit: ${DEFAULT_LOG_LINE_LIMIT:-1}
  friendlyName: ${LOG_SERVER_NAME:MyServer}
  logServers: ${LOG_SERVERS:self}
spring:
  application:
    name: "cribl-interview-logs"